Feature/homework 2
Ankoks/android_basic pull request #3
Opened 2021-04-27 15:23 UTC by Ankoks

2021-05-16 18:50 UTC, baidala requested changes
есть баг при нажатии на сердечко на основном списке - выделяется не та звездочка, на которую нажимали.
общий принцип работы адаптера -   список с фильмами из МейнАктивити передается в адаптер. в адаптере в viewHolder.bind  по параметру  MovieInfo.isFavourite  назначаете  иконку ic_baseline_favorite_border_24/ic_baseline_favorite_24.  при нажатии на сердечко  в модели MovieInfo  меняете параметр isFavourite.  и запрашиваете обновление  notifyDataSetChanged().  в акивити в данном случае не нужно  прокидывать коллбек.

2021-05-16 18:50 UTC, baidala commented on app/src/main/java/ru/ankoks/moviessearch/domain/MovieInfo.kt
> +class MovieInfo(val title: String, val description: String, var image: Int, var clicked: Boolean = false, var isFavourite: Boolean = false) : Parcelable
лучше использовать data class   для моделей данных

2021-05-16 18:50 UTC, baidala commented on app/src/main/java/ru/ankoks/moviessearch/MovieAdapter.kt
> +    override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): RecyclerView.ViewHolder {
добавляйте пустую строку  чтобы разделить код на логические части

2021-05-16 18:50 UTC, baidala commented on app/src/main/java/ru/ankoks/moviessearch/MovieAdapter.kt
> +                favouriteClickListener(movieInfo, favourite)
viewHolder.bind  по isFavourite  назначаете иконку, а здесь достаточно  изменить параматр в модели и запросить обновление списка 
```
movieInfo.isFavourite = !movieInfo.isFavourite
notifyDataSetChanged()
```

2021-05-16 18:50 UTC, baidala commented on app/src/main/java/ru/ankoks/moviessearch/MovieVH.kt
> +
сделайте для избранного отдельный viewHolder 
а в этом добавьте
```
if (movieInfo.isFavourite) {
            favImg.setImageResource(R.drawable.ic_baseline_favorite_border_24)
} else {
            favImg.setImageResource(R.drawable.ic_baseline_favorite_24)
}
```

2021-05-17 09:57 UTC, Ankoks commented on app/src/main/java/ru/ankoks/moviessearch/domain/MovieInfo.kt
> +class MovieInfo(val title: String, val description: String, var image: Int, var clicked: Boolean = false, var isFavourite: Boolean = false) : Parcelable
Переделал, но на лекции говорили что Parcelable класс работает быстрее и лучше его использовать вместо Serializable

2021-05-17 09:58 UTC, Ankoks commented on app/src/main/java/ru/ankoks/moviessearch/MovieAdapter.kt
> +    override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): RecyclerView.ViewHolder {
Добавил

2021-05-17 10:20 UTC, Ankoks commented on app/src/main/java/ru/ankoks/moviessearch/MovieVH.kt
> +
Перенес логику с сердечком в холдер.

2021-05-17 10:20 UTC, Ankoks commented on app/src/main/java/ru/ankoks/moviessearch/MovieAdapter.kt
> +                favouriteClickListener(movieInfo, favourite)
Добавил холдер для избранных, поменял логику в колбек листенера.

2021-05-18 13:32 UTC, baidala approved these changes
все ок. можно мержить

2021-05-18 16:23 UTC, merged