Feature/homework 3
Ankoks/android_basic pull request #4
Opened 2021-05-16 14:50 UTC by Ankoks

2021-05-28 09:37 UTC, baidala requested changes
креш при повороте екрана. нужен дефолтный конструктор. пустой.
java.lang.RuntimeException: Unable to start activity ComponentInfo{ru.ankoks.moviessearch/ru.ankoks.moviessearch.MainActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment ru.ankoks.moviessearch.fragments.MoviesFragment: could not find Fragment constructor
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3271)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3410)
        at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5280)
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5188)
        at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2017)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7397)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

2021-05-28 09:51 UTC, baidala requested changes
нужно исправить креш при повороте екрана  и подправить разметку активити

2021-05-28 09:51 UTC, baidala commented on app/src/main/AndroidManifest.xml
>          <activity android:name=".MovieActivity" />
из манифеста старое нужно удалить

2021-05-28 09:51 UTC, baidala commented on app/src/main/res/layout/activity_main.xml
> +    <FrameLayout
разметка немного не такая - 
1.FrameLayout  ( android:layout_height="0dp"  и привязан к  верху  BottomNavigationView)
2. BottomNavigationView (не в FrameLayout)
тогда у вас  FrameLayout будет растягиватся под любой екран и не налазить на меню
```

<FrameLayout
        android:id="@+id/fragmentContainer"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        app:layout_constraintTop_toTopOf="parent"
        app:layout_constraintBottom_toTopOf="@id/bottom_navigation"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintEnd_toEndOf="parent"/>
    <com.google.android.material.bottomnavigation.BottomNavigationView
        android:id="@+id/bottom_navigation"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_gravity="bottom"
        app:menu="@menu/bottom_navigation_menu"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintBottom_toBottomOf="parent"/>
```

2021-05-28 15:58 UTC, Ankoks commented on app/src/main/AndroidManifest.xml
>          <activity android:name=".MovieActivity" />
Удалил ненужное.

2021-05-28 16:00 UTC, Ankoks commented on app/src/main/res/layout/activity_main.xml
> +    <FrameLayout
Поправил.

2021-05-30 14:47 UTC, baidala approved these changes
задание выполнено. можно мержить

2021-05-30 16:59 UTC, merged